const blogPosts = [
    // ====== CŨ ======
    {
      id: 1,
      title: "🚀 Responsive Layout với Flexbox",
      desc: "Công thức Flexbox responsive: wrap + gap + flex-basis, dễ maintain.",
      tags: ["Frontend", "CSS", "Flexbox"],
      framework: "Vanilla",
      category: "Frontend",
      date: "2025-12-27",
      image: "./assets/blog/flexbox.jpg",
      url: "blog/flexbox-responsive.html",
    },
    {
      id: 2,
      title: "⚡ NodeJS + Express REST API cơ bản",
      desc: "Tạo REST API nhanh với Express, cấu trúc sạch và dễ mở rộng CRUD.",
      tags: ["Backend", "NodeJS", "Express"],
      framework: "Express",
      category: "Backend",
      date: "2025-12-26",
      image: "./assets/blog/node.jpg",
      url: "blog/node-express-api.html",
    },
    {
      id: 3,
      title: "🔥 TypeScript cơ bản cho Frontend Developer",
      desc: "Nắm chắc type/interface/union để code Frontend ít bug hơn.",
      tags: ["Frontend", "TypeScript"],
      framework: "TypeScript",
      category: "Frontend",
      date: "2025-12-25",
      image: "./assets/blog/typescript.jpg",
      url: "blog/typescript-basic.html",
    },
  
    // ====== 15 BÀI MỚI ======
    {
      id: 4,
      title: "🎨 CSS Grid Layout nhanh trong 5 phút",
      desc: "Tạo layout 2 chiều với Grid: auto-fit + minmax cực hữu dụng.",
      tags: ["Frontend", "CSS", "Grid"],
      framework: "Vanilla",
      category: "Frontend",
      date: "2025-12-24",
      image: "./assets/blog/grid.jpg",
      url: "blog/css-grid-quick.html",
    },
    {
      id: 5,
      title: "🧠 JavaScript: Closure là gì? (Ví dụ thực tế)",
      desc: "Hiểu closure qua ví dụ counter + module pattern.",
      tags: ["Frontend", "JavaScript"],
      framework: "Vanilla",
      category: "Frontend",
      date: "2025-12-23",
      image: "./assets/blog/closure.jpg",
      url: "blog/js-closure.html",
    },
    {
      id: 6,
      title: "⚡ Async/Await + Try/Catch chuẩn bài",
      desc: "Viết async code sạch, xử lý lỗi gọn, tránh callback hell.",
      tags: ["Frontend", "JavaScript", "Async"],
      framework: "Vanilla",
      category: "Frontend",
      date: "2025-12-22",
      image: "./assets/blog/async.jpg",
      url: "blog/async-await.html",
    },
    {
      id: 7,
      title: "🧩 React: useState/useEffect đúng cách",
      desc: "Mẫu code phổ biến + lỗi thường gặp + cách fix.",
      tags: ["Frontend", "React", "Hooks"],
      framework: "React",
      category: "Frontend",
      date: "2025-12-21",
      image: "./assets/blog/react-hooks.jpg",
      url: "blog/react-hooks.html",
    },
    {
      id: 8,
      title: "🧱 React: Component Patterns (Presentational vs Container)",
      desc: "Tách UI và logic giúp project dễ scale và dễ test.",
      tags: ["Frontend", "React", "Architecture"],
      framework: "React",
      category: "Frontend",
      date: "2025-12-20",
      image: "./assets/blog/react-pattern.jpg",
      url: "blog/react-patterns.html",
    },
    {
      id: 9,
      title: "🧪 Unit Test đơn giản với Jest (ví dụ)",
      desc: "Test function nhanh, hiểu expect, describe, it.",
      tags: ["Frontend", "Testing", "Jest"],
      framework: "Jest",
      category: "Frontend",
      date: "2025-12-19",
      image: "./assets/blog/jest.jpg",
      url: "blog/jest-unit-test.html",
    },
    {
      id: 10,
      title: "🔐 JWT Authentication: Flow dễ hiểu",
      desc: "Access token, refresh token, middleware verify token.",
      tags: ["Backend", "Auth", "JWT"],
      framework: "Express",
      category: "Backend",
      date: "2025-12-18",
      image: "./assets/blog/jwt.jpg",
      url: "blog/jwt-auth-flow.html",
    },
    {
      id: 11,
      title: "📦 REST API chuẩn: status code + response format",
      desc: "Chuẩn hóa response giúp frontend dùng dễ và debug nhanh.",
      tags: ["Backend", "API", "BestPractice"],
      framework: "Express",
      category: "Backend",
      date: "2025-12-17",
      image: "./assets/blog/rest.jpg",
      url: "blog/rest-best-practice.html",
    },
    {
      id: 12,
      title: "🗄️ PostgreSQL: SELECT/JOIN cơ bản (thực tế)",
      desc: "JOIN bảng users + orders + GROUP BY đơn giản.",
      tags: ["Backend", "SQL", "PostgreSQL"],
      framework: "PostgreSQL",
      category: "Backend",
      date: "2025-12-16",
      image: "./assets/blog/postgresql.jpg",
      url: "blog/postgresql-join.html",
    },
    {
      id: 13,
      title: "🧰 Git cơ bản cho teamwork",
      desc: "branch, merge, rebase, stash, commit message chuẩn.",
      tags: ["Tools", "Git"],
      framework: "Git",
      category: "Tools",
      date: "2025-12-15",
      image: "./assets/blog/git.jpg",
      url: "blog/git-teamwork.html",
    },
    {
      id: 14,
      title: "🚀 Deploy Web lên Vercel trong 3 phút",
      desc: "Deploy frontend nhanh + cấu hình build + domain free.",
      tags: ["DevOps", "Deploy", "Vercel"],
      framework: "Vercel",
      category: "DevOps",
      date: "2025-12-14",
      image: "./assets/blog/vercel.jpg",
      url: "blog/deploy-vercel.html",
    },
    {
      id: 15,
      title: "⚙️ Next.js: Routing + Page 구조 cực nhanh",
      desc: "Hiểu file-based routing, dynamic route, layout.",
      tags: ["Frontend", "NextJS", "Routing"],
      framework: "NextJS",
      category: "Frontend",
      date: "2025-12-13",
      image: "./assets/blog/nextjs.jpg",
      url: "blog/nextjs-routing.html",
    },
    {
      id: 16,
      title: "🌈 TailwindCSS: Workflow cực nhanh",
      desc: "Utility-first giúp bạn build UI nhanh hơn nhiều.",
      tags: ["Frontend", "CSS", "Tailwind"],
      framework: "Tailwind",
      category: "Frontend",
      date: "2025-12-12",
      image: "./assets/blog/tailwind.jpg",
      url: "blog/tailwind-workflow.html",
    },
    {
      id: 17,
      title: "🧠 Clean Code: đặt tên biến và function",
      desc: "Một vài quy tắc nhỏ nhưng nâng chất lượng code rõ rệt.",
      tags: ["Software", "CleanCode"],
      framework: "General",
      category: "Software",
      date: "2025-12-11",
      image: "./assets/blog/cleancode.jpg",
      url: "blog/clean-code-naming.html",
    },
    {
      id: 18,
      title: "🛡️ CORS là gì? Fix lỗi CORS nhanh",
      desc: "Giải thích dễ hiểu + cách fix Express CORS đúng chuẩn.",
      tags: ["Backend", "CORS", "Express"],
      framework: "Express",
      category: "Backend",
      date: "2025-12-10",
      image: "./assets/blog/cors.jpg",
      url: "blog/cors-fix.html",
    },
  ];
  